spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    mode: HTML
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB
  mvc:
    mime-type.**.js: application/javascript

project:
  product:
    upload-dir: /opt/greenbayenergy/ServiceVixDocs/project_image/products
  service:
    upload-dir: /opt/greenbayenergy/ServiceVixDocs/project_image/services
  organization:
    upload-dir: /opt/greenbayenergy/ServiceVixDocs/project_image/organization
  user:
    upload-dir: /opt/greenbayenergy/ServiceVixDocs/project_image/user
  temp:
    upload-dir: /opt/greenbayenergy/ServiceVixDocs/project_image/temp
     
admin:
  baseURL: https://servicevix.rogpe.tech
  
jwt:
  secret:
    key: ${JWT_SECRET_KEY}
  expiration:
    time:
      ms: 3600000

super:
  admin:
    count: 2
    
estimate:
  subject: Estimate Subject

invoice:
  subject: Invoice Subject
  
server:
  port: 8081

staff:
  password: ${STAFF_DEFAULT_PASSWORD}
    
role:
  organization: ORGANIZATION

resource:
  image:
    path: file:///opt/greenbayenergy/ServiceVixDocs/project_image/

image:
  base:
    path: /opt/greenbayenergy/ServiceVixDocs/project_image/

thymeleaf:
  resources:
    static-locations: file:src/main/resources/static/
    cache:
      period: '0'
  thymeleaf:
    encoding: UTF-8
    prefix: file:src/main/resources/templates/
    cache: 'false'
    mode: HTML
logging:
  level:
    root: DEBUG

forgot-password-message:
  prefix: Hi we got a request to change your password for Service Vix application. We have generated a random password for you that is 
  suffix: .Now you can login with your account by using this password. Thank You!
