spring:
  #Database Configuration
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/service_vix?createDatabaseIfNotExist=true
    username: root
    password:
  #Email Cnfiguration 
  mail:
    host: smtp.gmail.com
    port: 587
    #username: kailashsirswal5@gmail.com
    #password: jmgbgssvabqjkhyx
    username: greenbaynotification@gmail.com
    password: xghjmybiwuxjegka
    properties:
      mail:
       smtp:
        auth: true
        starttls: 
         enable: true
    
  #JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  # Thymeleaf Configuration
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    mode: HTML
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB
  mvc:
        mime-type.**.js: application/javascript
        
#Images directory configuration
project:
  product:
    upload-dir: D:/ServiceVixDocs/project_image/products
  service:
    upload-dir: D:/ServiceVixDocs/project_image/services
  organization:
    upload-dir: D:/ServiceVixDocs/project_image/organizations
  user:
    upload-dir: D:/ServiceVixDocs/project_image/users
  temp:
    upload-dir: D:/ServiceVixDocs/project_image/temp
     
#Admin configuration
admin:
  baseURL: http://localhost:8080

# JWT Configuration
jwt:
  secret:
    key: MbQeThWmZq4t7w!z==========S3r^!seV|x
  expiration:
    time:
      ms: 7200000 #2 hours

# Super admins for application
super:
  admin:
    count: 2
    
#Estimate Email Subject
estimate:
  subject: Estimate Subject
#Invoice Email Subject
invoice:
  subject: Invoice
  
#Staff Default Password
staff:
  password: Staff@123
    
#Pre Roles Configuration
role:
  organization: ORGANIZATION
  
#Read files from local directory
resource:
   image:
     path: file:///D:/ServiceVixDocs/project_image/
image:
  base:
    path: D:/ServiceVixDocs/project_image/
#thymeleaf resource config
  resources:
    static-locations: file:src/main/resources/static/
    cache:
      period: '0'
  thymeleaf:
    encoding: UTF-8
    prefix: file:src/main/resources/templates/
    cache: 'false'
    mode: HTML

#Forgot Password message
forgot-password-message:
  prefix: Hi we got a request to change your poassword for Service Vix application. We have generated a random password for you that is 
  suffix: .Now you can login with your account by use this password. Thank You!
